// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcxnqqjcigrnckknpkni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjeG5xcWpjaWdybmNra25wa25pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwOTU4MDcsImV4cCI6MjA2MDY3MTgwN30.8MpFghzRT1QjzPLQfXZngB2QQRNsjuGoYR-v_3m667Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);